depth = -y;
alarm[0] = room_speed * 2.5;
alarm[1] = room_speed;
instance_create_depth(x, y, 0, obj_bedroom_event_roomglow);
particle_system = part_system_create();
part_system_depth(particle_system, depth);
effect_drop = part_type_create();
part_type_sprite(effect_drop, spr_spark, false, false, true);
part_type_size(effect_drop, 1, 1, 0, 0);
part_type_life(effect_drop, 15, 15);
part_type_alpha1(effect_drop, 1);
part_type_gravity(effect_drop, 0.3, 270);
part_type_direction(effect_drop, 0, 360, 0, 5);
part_type_speed(effect_drop, 1, 4, 0, 0);
part_type_orientation(effect_drop, 0, 0, 0, 0, true);
effect_hit = part_type_create();
part_type_sprite(effect_hit, spr_sparkhit, true, true, false);
part_type_size(effect_hit, 1, 1, 0, 0);
part_type_life(effect_hit, 10, 15);
part_type_alpha3(effect_hit, 1, 1, 0);
part_type_death(effect_drop, 1, effect_hit);
particle_emitter = part_emitter_create(particle_system);
