event_inherited();
button_color = 0;
button_merge = 0;
button_sound = snd_global_vwoom;
x_anchor = x;
y_anchor = y;
x_max = 3;
y_max = 5;
x_freq = 0.04;
y_freq = 0.03;
move_counter = 0;
particle_system = part_system_create();
part_system_depth(particle_system, depth - 1);
part_angle = irandom(360);
x_length = x + lengthdir_x(100, part_angle);
y_length = y + lengthdir_y(100, part_angle);
part_dir = point_direction(x_length, y_length, x, y);
effect_fall = part_type_create();
part_type_sprite(effect_fall, spr_pixel, false, false, false);
part_type_size(effect_fall, 2, 6, 0, 0);
part_type_speed(effect_fall, 1, 2, 0, 0);
part_type_life(effect_fall, 40, 50);
part_type_alpha3(effect_fall, 0, 1, 0);
part_type_direction(effect_fall, part_dir, part_dir, 0, 10);
part_type_orientation(effect_fall, 0, 360, choose(-5, 5), 0, true);
