event_inherited();
player_x = 528;
player_y = 285;
next_room = home_hallway;
next_color = 0;
fadein_timer = 0.02;
fadeout_timer = 0.02;
fadepause_timer = 0.02;
fadeout_amount = 0.05;
fadein_amount = 0.05;
snd_file = snd_stairs_up;
snd_volume = 0.15;
snd_pitch = 1;
