function game_init()
{
    gml_release_mode(true);
    global.debug_version = 0;
    global.last_key = 0;
    global.last_controller = 0;
    randomize();
    storyline_vars();
    global.steam_screenshots = 0;
    global.steam_achievements = 0;
    global.pirated_game = 0;
    global.volume_main = 0.5;
    global.up_key_button = "W";
    global.left_key_button = "A";
    global.down_key_button = "S";
    global.right_key_button = "D";
    global.accept_key_button = "Z";
    global.cancel_key_button = "X";
    global.controller_button_down = 32769;
    global.controller_button_right = 32770;
    global.controller_button_left = 32771;
    global.controller_button_up = 32772;
    global.controller_type = 0;
    global.fullscreen_active = 0;
    global.up_key = 0;
    global.left_key = 0;
    global.down_key = 0;
    global.right_key = 0;
    global.up_key_pressed = 0;
    global.left_key_pressed = 0;
    global.down_key_pressed = 0;
    global.right_key_pressed = 0;
    global.a_key = 0;
    global.b_key = 0;
    global.x_key = 0;
    global.y_key = 0;
    global.start_key = 0;
    global.gamepad_axis_lh = 0;
    global.gamepad_axis_lv = 0;
    global.gamepad_axis_rh = 0;
    global.gamepad_axis_rv = 0;
    global.accept_key = 0;
    global.cancel_key = 0;
    global.accept_key_held = 0;
    global.any_key = 0;
    global.any_mouse = 0;
    global.any_controller = 0;
    global.gamepad_index = -100;
    global.control_type = 0;
    global.player_speed_cur = 2;
    global.player_speed_nrm = 2;
    global.player_clothing = "pajama";
    global.player_frozen = 0;
    global.player_direction = 3;
    global.player_moving = 0;
    global.shaders_active = 0;
    
    if (shader_is_compiled(shd_grayscale))
        global.shaders_active = 1;
    
    global.surface_offset_x = 0;
    global.surface_offset_y = 0;
    global.shadow_surface = -4;
    global.arena_surface = -4;
    global.darkening_active = 1;
    global.world_seed = string(random_get_seed());
    global.start_room = home_bedroom;
    global.start_x = 0;
    global.start_y = 0;
    global.save_file_name = "heartbound_save.thor";
    global.credits_file_name = "Credits.txt";
    global.menu_active = 0;
    global.current_menu = 0;
    global.cursor_active = 0;
    global.cursor_model = spr_cursor_heart;
    global.combat_active = 0;
    global.player_hp_cur = 10;
    global.player_hp_max = 10;
    global.player_hp_check = 0;
    global.enemy_hp_cur = 20;
    global.enemy_hp_max = 20;
    global.enemy_hp_check = 0;
    global.current_talker = -4;
    global.conv_talking = 0;
    global.game_language = "ENUS";
    global.language_type = 0;
    global.language_known = 0;
    global.language_map = 0;
    global.option_number = 0;
    dialog_talky_init();
    dialog_voice_init();
    letter_map_init();
    glyph_map_init();
    global.wiggletext_active = 1;
    global.options_file_name = "options_1.thor";
    load_options();
    window_set_fullscreen(global.fullscreen_active);
}
