settings_active = 0;
menu_last_index = global.current_menu;
menu_last_active = global.menu_active;
menu_last_selected = obj_controller_buttons.selected_button;
menu_last_mouse = global.cursor_active;
menu_last_frozen = global.player_frozen;
layer_id = layer_get_id("BG_Moving");
layer_last_hspeed = layer_get_hspeed(layer_id);
layer_last_vspeed = layer_get_vspeed(layer_id);
layer_vspeed(layer_id, 0);
layer_hspeed(layer_id, 0);
obj_mouse.image_alpha = 0;
global.menu_active = 0;
global.player_frozen = 1;
cam_offset = 10;
cam_id = view_camera[view_current];
cam_x = camera_get_view_x(cam_id) - cam_offset;
cam_y = camera_get_view_y(cam_id) - cam_offset;
cam_w = 640 + (cam_offset * 2);
cam_h = 360 + (cam_offset * 2);
cam_center_x = cam_w * 0.5;
cam_center_y = cam_h * 0.5;
size_cur = 0;
size_step = 20;
size_max = floor(cam_w * 1.2);
alarm[0] = 2;
